# Generated by Django 5.2 on 2025-04-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('name', 'department')},
        ),
        migrations.AlterUniqueTogether(
            name='college',
            unique_together={('name', 'campus')},
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'college')},
        ),
    ]
