# Generated by Django 5.2 on 2025-04-14 13:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_student_campus_alter_student_college_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'teacher', 'attendance_type')},
        ),
    ]
