# Generated by Django 5.2 on 2025-04-21 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name_plural': 'Classes'},
        ),
    ]
