# Generated by Django 5.2 on 2025-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='laptop_serial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
