# Generated by Django 5.2 on 2025-04-23 15:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_student_laptop_serial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name_plural': 'Campuses'},
        ),
        migrations.CreateModel(
            name='StudentEntryExit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('entry_exit', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
