# Generated by Django 5.2 on 2025-04-23 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_campus_options_studententryexit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentEntryExit',
        ),
    ]
