# Generated by Django 5.2 on 2025-05-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_studententry'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='laptop_model',
            field=models.CharField(blank=True, choices=[('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('MacBook', 'MacBook'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('Other', 'Other')], max_length=20, null=True, verbose_name='Laptop Model'),
        ),
    ]
