# Generated by Django 5.2 on 2025-05-12 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studententry',
            options={'ordering': ['-entry_time'], 'verbose_name_plural': 'Entries'},
        ),
        migrations.RemoveField(
            model_name='studententry',
            name='gatekeeper',
        ),
        migrations.AddField(
            model_name='studententry',
            name='manual_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='entry_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
