# Generated by Django 5.2 on 2025-05-12 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studententry_gatekeeper'),
    ]

    operations = [
        migrations.AddField(
            model_name='studententry',
            name='entry_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
