# Generated by Django 5.2 on 2025-05-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_studententry_entry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studententry',
            name='entry_date',
        ),
    ]
