# Generated by Django 5.2 on 2025-05-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_studententry_entry_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studententry',
            options={'ordering': ['-entry_date', '-entry_time']},
        ),
        migrations.AlterField(
            model_name='studententry',
            name='entry_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
