# Generated by Django 5.2 on 2025-05-12 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_studententry_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studententry',
            options={'ordering': ['-entry_time'], 'verbose_name_plural': 'Student Entries'},
        ),
        migrations.RemoveField(
            model_name='studententry',
            name='entry_date',
        ),
        migrations.RemoveField(
            model_name='studententry',
            name='manual_entry',
        ),
        migrations.AlterField(
            model_name='studententry',
            name='entry_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studententry',
            name='gatekeeper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
