# Generated by Django 5.2 on 2025-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('gatekeeper', 'Gatekeeper'), ('teacher', 'Teacher'), ('registrar', 'Registrar'), ('finance', 'Finance')], default='', max_length=20),
        ),
    ]
