# Generated by Django 5.2 on 2025-05-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('default', 'choose role'), ('admin', 'Admin'), ('gatekeeper', 'Gatekeeper'), ('teacher', 'Teacher'), ('registrar', 'Registrar'), ('finance', 'Finance')], default='', max_length=20),
        ),
    ]
